version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: damira_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: damira_pharma
    ports:
      - "5432:5432"
    volumes:
      - damira_postgres_data:/var/lib/postgresql/data

volumes:
  damira_postgres_data: